### ISSUE TITLE
Milestone 3 - Feedback

### ISSUE THREAD

**Issue by danielramandi** [UBC-MDS/chocolate_rating#87]
**Congratulations on finishing milestone 3!** We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

- [ ] Target all could be simplified by writing something like all: <report_target>. - 2 mechanics

**Comment:** You can only use the final report html for the ‘all’ section. Also, add a comment somewhere that the clean commands are written for which OS. `-rf` is not defined in windows I think. Overall, well done! Works like a charm!

**Comment by robindhillon1** [comment]
Hi Daniel, I specifically went to Florencia's office hours and she confirmed everything was good. She said as long as everything works as intended (which it does like you said), we have nothing to worry about. There was no mention of simplifying or efficiency (although what we did was efficient, I believe). So although it's only 2 marks, I don't think it's justified to be honest.

**Comment by markusnam** [comment]
Hi Daniel, on top of Robin's reply, I would like to say that our work was based on the `breast_cancer` project that Florencia always tells us to refer to.
Here is the Makefile from the `breast_cancer` project. [https://github.com/ttimbers/breast_cancer_predictor/blob/master/Makefile](https://github.com/ttimbers/breast_cancer_predictor/blob/master/Makefile)
I would say our format is similar to the official reference.
